export const GET_BLOG_REQUEST = "GET_BLOG_REQUEST";
export const GET_BLOG_SUCCESS = "GET_BLOG_SUCCESS";
export const GET_BLOG_FAILURE = "GET_BLOG_FAILURE";

export const CREATE_BLOG_REQUEST = "CREATE_BLOG_REQUEST";
export const CREATE_BLOG_SUCCESS = "CREATE_BLOG_SUCCESS";
export const CREATE_BLOG_FAILURE = "CREATE_BLOG_FAILURE";
export const CREATE_BLOG_RESET = "CREATE_BLOG_RESET";

export const GET_SINGLE_BLOG_REQUEST = "GET_SINGLE_BLOG_REQUEST";
export const GET_SINGLE_BLOG_SUCCESS = "GET_SINGLE_BLOG_SUCCESS";
export const GET_SINGLE_BLOG_FAILURE = "GET_SINGLE_BLOG_FAILURE";


export const DELETE_BLOG_REQUEST = 'DELETE_BLOG_REQUEST'
export const DELETE_BLOG_SUCCESS = 'DELETE_BLOG_SUCCESS'
export const DELETE_BLOG_RESET = 'DELETE_BLOG_RESET'
export const DELETE_BLOG_FAIL = 'DELETE_BLOG_FAIL'

export const ADMIN_BLOGS_REQUEST = 'ADMIN_BLOGS_REQUEST'
export const ADMIN_BLOGS_SUCCESS = 'ADMIN_BLOGS_SUCCESS'
export const ADMIN_BLOGS_FAIL = 'ADMIN_BLOGS_FAIL'



export const CLEAR_ERRORS = "CLEAR_ERRORS";
