export const CREATE_COURSE_REQUEST = "CREATE_COURSE_REQUEST";
export const CREATE_COURSE_SUCCESS = "CREATE_COURSE_SUCCESS";
export const CREATE_COURSE_FAILURE = "CREATE_COURSE_FAILURE";
export const CREATE_COURSE_RESET = "CREATE_COURSE_RESET";

export const GET_COURSE_REQUEST = "GET_COURSE_REQUEST";
export const GET_COURSE_SUCCESS = "GET_COURSE_SUCCESS";
export const GET_COURSE_FAILURE = "GET_COURSE_FAILURE";


export const GET_SINGLE_COURSE_REQUEST = "GET_SINGLE_COURSE_REQUEST";
export const GET_SINGLE_COURSE_SUCCESS = "GET_SINGLE_COURSE_SUCCESS";
export const GET_SINGLE_COURSE_FAILURE = "GET_SINGLE_COURSE_FAILURE";

export const ADMIN_COURSE_REQUEST = 'ADMIN_COURSE_REQUEST'
export const ADMIN_COURSE_SUCCESS = 'ADMIN_COURSE_SUCCESS'
export const ADMIN_COURSE_FAIL = 'ADMIN_COURSE_FAIL'

export const DELETE_COURSE_REQUEST = 'DELETE_COURSE_REQUEST'
export const DELETE_COURSE_SUCCESS = 'DELETE_COURSE_SUCCESS'
export const DELETE_COURSE_FAIL = 'DELETE_COURSE_FAIL'
export const DELETE_COURSE_RESET = 'DELETE_COURSE_RESET'


export const CLEAR_ERRORS = "CLEAR_ERRORS";