export const CREATE_MESSAGE_REQUEST = "CREATE_MESSAGE_REQUEST";
export const CREATE_MESSAGE_SUCCESS = "CREATE_MESSAGE_SUCCESS";
export const CREATE_MESSAGE_FAILURE = "CREATE_MESSAGE_FAILURE";
export const CREATE_MESSAGE_RESET = "CREATE_MESSAGE_RESET";

export const GET_MESSAGE_REQUEST = "GET_MESSAGE_REQUEST";
export const GET_MESSAGE_SUCCESS = "GET_MESSAGE_SUCCESS";
export const GET_MESSAGE_FAILURE = "GET_MESSAGE_FAILURE";
export const GET_MESSAGE_RESET = "GET_MESSAGE_RESET";

export const DELETE_MESSAGE_REQUEST = 'DELETE_MESSAGE_REQUEST'
export const DELETE_MESSAGE_SUCCESS = 'DELETE_MESSAGE_SUCCESS'
export const DELETE_MESSAGE_RESET = 'DELETE_MESSAGE_RESET'
export const DELETE_MESSAGE_FAIL = 'DELETE_MESSAGE_FAIL'

export const CLEAR_ERRORS = "CLEAR_ERRORS";
