export const CREATE_PDF_REQUEST = "CREATE_PDF_REQUEST";
export const CREATE_PDF_SUCCESS = "CREATE_PDF_SUCCESS";
export const CREATE_PDF_FAILURE = "CREATE_PDF_FAILURE";
export const CREATE_PDF_RESET = "CREATE_PDF_RESET";

export const GET_PDF_REQUEST = "GET_PDF_REQUEST";
export const GET_PDF_SUCCESS = "GET_PDF_SUCCESS";
export const GET_PDF_FAILURE = "GET_PDF_FAILURE";
export const GET_PDF_RESET = "GET_PDF_RESET";

export const DELETE_PDF_REQUEST = 'DELETE_PDF_REQUEST'
export const DELETE_PDF_SUCCESS = 'DELETE_PDF_SUCCESS'
export const DELETE_PDF_RESET = 'DELETE_PDF_RESET'
export const DELETE_PDF_FAILURE = 'DELETE_PDF_FAILURE'

export const CLEAR_ERRORS = "CLEAR_ERRORS";
